added 2021 org link
nishantwrp/gsoc-organizations pull request #49
Opened 2021-02-20 09:53 UTC by singlamohit1

2021-02-20 09:55 UTC, nishantwrp requested changes

2021-02-20 09:55 UTC, nishantwrp commented on src/components/notification.jsx
> +const MessageExampleInfo = () => {
`MessageExampleInfo` ?

2021-02-20 09:55 UTC, nishantwrp commented on src/pages/index.jsx
> +      </Grid>
Do we need `Grid` and `index-org-cards-grid` class?

2021-02-20 10:03 UTC, singlamohit1 commented on src/components/notification.jsx
> +const MessageExampleInfo = () => {
done

2021-02-20 10:04 UTC, singlamohit1 commented on src/pages/index.jsx
> +      </Grid>
yes

2021-03-10 03:16 UTC, nishantwrp approved these changes

2021-03-10 03:16 UTC, merged