feat: ui for project proposal
nishantwrp/gsoc-organizations pull request #72
Opened 2022-05-15 08:55 UTC by beingnoble03

This PR adds button for project proposal in the past projects card.

2022-05-15 08:56 UTC, beingnoble03 commented
@nishantwrp PTAL.

2022-05-16 18:03 UTC, singlamohit1 commented
@beingnoble03 LGTM 
@nishantwrp u can have final look and then merge

2022-05-20 17:23 UTC, beingnoble03 commented
@nishantwrp PTAL.

2022-05-20 19:59 UTC, nishantwrp commented
Can you adjust the height of the buttons to be same?

<img width="1440" alt="Screenshot 2022-05-21 at 1 28 44 AM" src="https://user-images.githubusercontent.com/36989112/169602306-cb522621-05ca-492a-b46b-845bcda7f6ff.png">

2022-05-21 04:51 UTC, beingnoble03 commented
@nishantwrp PTAL. I fixed to height of buttons to 50px.

2022-05-23 19:20 UTC, nishantwrp requested changes
Thanks @beingnoble03, left a few comments. ptal!

2022-05-23 19:20 UTC, nishantwrp commented on src/components/project-card.css
> +  margin-top: 10px;
Reduce the margin to `5px`.

2022-05-23 19:20 UTC, nishantwrp commented on src/components/project-card.css
> +  height: 50px;
```suggestion
  height: 100%;
```

2022-05-23 19:20 UTC, nishantwrp commented on src/components/project-card.css
> +  height: 100%;
```suggestion
```

2022-05-23 19:20 UTC, nishantwrp commented on src/components/project-card.jsx
> +              Project Proposal
Should we change it to `Proposal` because we're not using `Project` prefix in any other links above

2022-05-24 07:01 UTC, beingnoble03 commented on src/components/project-card.jsx
> +              Project Proposal
Hmm.. Yes we can do that.

2022-05-24 07:02 UTC, beingnoble03 commented on src/components/project-card.css
> +  height: 50px;
Done

2022-05-24 07:02 UTC, beingnoble03 commented on src/components/project-card.css
> +  height: 100%;
done

2022-05-24 07:02 UTC, beingnoble03 commented on src/components/project-card.css
> +  margin-top: 10px;
Done

2022-05-24 10:12 UTC, nishantwrp approved these changes
lgtm, thanks @beingnoble03!

2022-05-24 10:12 UTC, merged